window.extraPassages = [
  {
    "canto": 2,
    "title": "The Descent and the Three Blessed Ladies",
    "lines": "Canto 2, scene 1",
    "classic": "Day was departing, and the embrowned air\n    Released the animals that are on earth\n    From their fatigues; and I the only one\nMade myself ready to sustain the war,\n    Both of the way and likewise of the woe,\n    Which memory that errs not shall retrace.\nO Muses, O high genius, now assist me!\n    O memory, that didst write down what I saw,\n    Here thy nobility shall be manifest!\nAnd I began: “Poet, who guidest me,\n    Regard my manhood, if it be sufficient,\n    Ere to the arduous pass thou dost confide me.\nThou sayest, that of Silvius the parent,\n    While yet corruptible, unto the world\n    Immortal went, and was there bodily.\nBut if the adversary of all evil\n    Was courteous, thinking of the high effect\n    That issue would from him, and who, and what,\nTo men of intellect unmeet it seems not;\n    For he was of great Rome, and of her empire\n    In the empyreal heaven as father chosen;\nThe which and what, wishing to speak the truth,\n    Were stablished as the holy place, wherein\n    Sits the successor of the greatest Peter.",
    "modern": "Evening was falling.\nThe dark air was letting every animal on earth\nrest from the work of the day.\n\nBut I alone was preparing myself\nfor a different kind of struggle:\nthe journey,\nand the suffering I would have to witness.\n\nThen I began to panic.\nI told Virgil that Aeneas had gone alive\ninto the world of the dead,\nand that made sense,\nbecause Rome and the Church\nwould one day come from his destiny.",
    "notes": "<div class=\"note-block\"><strong>What is happening:</strong> Canto II is Dante's crisis of confidence. Canto I ended with motion, but now Dante freezes before the journey truly begins.</div><div class=\"note-block\"><strong>Aeneas:</strong> Aeneas is the hero of Virgil's Aeneid. He goes to the underworld while alive and receives knowledge connected to Rome's future greatness.</div><div class=\"note-block\"><strong>Rome and Peter:</strong> Dante sees Rome as both imperial and sacred: the city of the Roman Empire and later the seat of Saint Peter's successor, the pope.</div>"
  },
  {
    "canto": 2,
    "title": "The Descent and the Three Blessed Ladies",
    "lines": "Canto 2, scene 2",
    "classic": "Upon this journey, whence thou givest him vaunt,\n    Things did he hear, which the occasion were\n    Both of his victory and the papal mantle.\nThither went afterwards the Chosen Vessel,\n    To bring back comfort thence unto that Faith,\n    Which of salvation’s way is the beginning.\nBut I, why thither come, or who concedes it?\n    I not Aeneas am, I am not Paul,\n    Nor I, nor others, think me worthy of it.\nTherefore, if I resign myself to come,\n    I fear the coming may be ill-advised;\n    Thou’rt wise, and knowest better than I speak.”\nAnd as he is, who unwills what he willed,\n    And by new thoughts doth his intention change,\n    So that from his design he quite withdraws,\nSuch I became, upon that dark hillside,\n    Because, in thinking, I consumed the emprise,\n    Which was so very prompt in the beginning.\n“If I have well thy language understood,”\n    Replied that shade of the Magnanimous,\n    “Thy soul attainted is with cowardice,\nWhich many times a man encumbers so,\n    It turns him back from honoured enterprise,\n    As false sight doth a beast, when he is shy.",
    "modern": "I also remembered Saint Paul,\nwho was taken up into Heaven\nand returned with strength for the Christian faith.\n\nBut I am not Aeneas,\nand I am not Paul.\nWho has allowed me to go?\nWho could think I am worthy?\n\nAs I thought about it,\nmy courage drained away.\nI became like someone\nwho changes his mind at the last moment\nand abandons what he had just decided to do.",
    "notes": "<div class=\"note-block\"><strong>Saint Paul:</strong> Paul was one of early Christianity's most important apostles. Dante is referring to the idea that Paul had a heavenly vision and returned strengthened for his mission.</div><div class=\"note-block\"><strong>Dante's fear:</strong> His logic is simple: Aeneas and Paul had world-historical religious missions. Dante does not understand why he, an ordinary frightened man, should receive a similar privilege.</div><div class=\"note-block\"><strong>Reader's clue:</strong> This is not false modesty. Dante really is asking whether this journey is authorized or just madness.</div>"
  },
  {
    "canto": 2,
    "title": "The Descent and the Three Blessed Ladies",
    "lines": "Canto 2, scene 3",
    "classic": "That thou mayst free thee from this apprehension,\n    I’ll tell thee why I came, and what I heard\n    At the first moment when I grieved for thee.\nAmong those was I who are in suspense,\n    And a fair, saintly Lady called to me\n    In such wise, I besought her to command me.\nHer eyes where shining brighter than the Star;\n    And she began to say, gentle and low,\n    With voice angelical, in her own language:\n‘O spirit courteous of Mantua,\n    Of whom the fame still in the world endures,\n    And shall endure, long-lasting as the world;\nA friend of mine, and not the friend of fortune,\n    Upon the desert slope is so impeded\n    Upon his way, that he has turned through terror,\nAnd may, I fear, already be so lost,\n    That I too late have risen to his succour,\n    From that which I have heard of him in Heaven.\nBestir thee now, and with thy speech ornate,\n    And with what needful is for his release,\n    Assist him so, that I may be consoled.\nBeatrice am I, who do bid thee go;\n    I come from there, where I would fain return;\n    Love moved me, which compelleth me to speak.",
    "modern": "Virgil understood me.\nHe said my soul was infected\nwith cowardice - the kind of fear\nthat makes people turn back\nfrom honorable things.\n\nThen he told me why he had come.\nHe had been among the souls in suspense\nwhen a beautiful, saintly lady called him.\nHer eyes shone brighter than a star,\nand her voice sounded angelic.",
    "notes": "<div class=\"note-block\"><strong>Cowardice:</strong> Virgil diagnoses Dante's hesitation as fear that disguises itself as careful thinking. Dante is reasoning, but fear is driving the reasoning.</div><div class=\"note-block\"><strong>Souls in suspense:</strong> Virgil is in Limbo, a place for worthy people who lack Christian salvation. We will see it more fully in Canto IV.</div><div class=\"note-block\"><strong>The saintly lady:</strong> The woman who calls Virgil is Beatrice. She is central to Dante's spiritual imagination.</div>"
  },
  {
    "canto": 2,
    "title": "The Descent and the Three Blessed Ladies",
    "lines": "Canto 2, scene 4",
    "classic": "When I shall be in presence of my Lord,\n    Full often will I praise thee unto him.’\n    Then paused she, and thereafter I began:\n‘O Lady of virtue, thou alone through whom\n    The human race exceedeth all contained\n    Within the heaven that has the lesser circles,\nSo grateful unto me is thy commandment,\n    To obey, if ’twere already done, were late;\n    No farther need’st thou ope to me thy wish.\nBut the cause tell me why thou dost not shun\n    The here descending down into this centre,\n    From the vast place thou burnest to return to.’\n‘Since thou wouldst fain so inwardly discern,\n    Briefly will I relate,’ she answered me,\n    ‘Why I am not afraid to enter here.\nOf those things only should one be afraid\n    Which have the power of doing others harm;\n    Of the rest, no; because they are not fearful.\nGod in his mercy such created me\n    That misery of yours attains me not,\n    Nor any flame assails me of this burning.\nA gentle Lady is in Heaven, who grieves\n    At this impediment, to which I send thee,\n    So that stern judgment there above is broken.",
    "modern": "The lady was Beatrice.\nShe told Virgil that her friend,\nwho was not a friend of fortune,\nwas blocked on the deserted slope\nand might already be too lost\nfor help to arrive in time.\n\nShe asked Virgil to use his noble speech\nand whatever else was needed\nto rescue him.\n\nLove moved her to speak.",
    "notes": "<div class=\"note-block\"><strong>Beatrice:</strong> Historically, Beatrice was a woman Dante loved and wrote about. In the Comedy she becomes much more: a heavenly figure representing grace, divine love, and revelation.</div><div class=\"note-block\"><strong>Not a friend of fortune:</strong> Dante is vulnerable, unlucky, and in danger. Beatrice sees him not as a hero but as someone beloved who needs rescue.</div><div class=\"note-block\"><strong>Love moved me:</strong> In Dante, holy love is active. It does not merely feel pity; it sends help.</div>"
  },
  {
    "canto": 2,
    "title": "The Descent and the Three Blessed Ladies",
    "lines": "Canto 2, scene 5",
    "classic": "In her entreaty she besought Lucia,\n    And said, “Thy faithful one now stands in need\n    Of thee, and unto thee I recommend him.”\nLucia, foe of all that cruel is,\n    Hastened away, and came unto the place\n    Where I was sitting with the ancient Rachel.\n“Beatrice” said she, “the true praise of God,\n    Why succourest thou not him, who loved thee so,\n    For thee he issued from the vulgar herd?\nDost thou not hear the pity of his plaint?\n    Dost thou not see the death that combats him\n    Beside that flood, where ocean has no vaunt?”\nNever were persons in the world so swift\n    To work their weal and to escape their woe,\n    As I, after such words as these were uttered,\nCame hither downward from my blessed seat,\n    Confiding in thy dignified discourse,\n    Which honours thee, and those who’ve listened to it.’\nAfter she thus had spoken unto me,\n    Weeping, her shining eyes she turned away;\n    Whereby she made me swifter in my coming;\nAnd unto thee I came, as she desired;\n    I have delivered thee from that wild beast,\n    Which barred the beautiful mountain’s short ascent.",
    "modern": "Virgil asked why Beatrice\nwas not afraid to descend from Heaven\ninto the depths.\n\nShe answered that only things\nthat can truly harm us\nshould be feared.\nBy God's mercy,\nthe misery and flames of Hell\ncould not touch her.\n\nThen she explained the chain of help:\nMary in Heaven cared,\nLucia was sent,\nand Lucia came to Beatrice,\ntelling her that Dante needed her.",
    "notes": "<div class=\"note-block\"><strong>Mary:</strong> Mary is the mother of Jesus and one of the most important figures in Catholic devotion. She often represents mercy and compassionate intercession.</div><div class=\"note-block\"><strong>Lucia:</strong> Saint Lucia, or Lucy, is associated with light and sight. In Dante she often suggests illuminating grace: help that lets a person see and move rightly.</div><div class=\"note-block\"><strong>Rachel:</strong> Rachel is a biblical figure traditionally associated with contemplation. Beatrice sitting with Rachel places her among blessed, contemplative souls.</div><div class=\"note-block\"><strong>The chain of mercy:</strong> Dante is saved not because he is strong, but because Heaven notices him: Mary moves Lucia, Lucia moves Beatrice, Beatrice moves Virgil.</div>"
  },
  {
    "canto": 2,
    "title": "The Descent and the Three Blessed Ladies",
    "lines": "Canto 2, scene 6",
    "classic": "What is it, then?  Why, why dost thou delay?\n    Why is such baseness bedded in thy heart?\n    Daring and hardihood why hast thou not,\nSeeing that three such Ladies benedight\n    Are caring for thee in the court of Heaven,\n    And so much good my speech doth promise thee?”\nEven as the flowerets, by nocturnal chill,\n    Bowed down and closed, when the sun whitens them,\n    Uplift themselves all open on their stems;\nSuch I became with my exhausted strength,\n    And such good courage to my heart there coursed,\n    That I began, like an intrepid person:\n“O she compassionate, who succoured me,\n    And courteous thou, who hast obeyed so soon\n    The words of truth which she addressed to thee!\nThou hast my heart so with desire disposed\n    To the adventure, with these words of thine,\n    That to my first intent I have returned.\nNow go, for one sole will is in us both,\n    Thou Leader, and thou Lord, and Master thou.”\n    Thus said I to him; and when he had moved,\nI entered on the deep and savage way.",
    "modern": "After hearing this,\nVirgil came quickly to Dante.\n\nHe asked why Dante was still delaying.\nWhy be cowardly,\nwhen three blessed women in Heaven\nwere caring for him?\n\nDante's courage returned\nlike flowers opening again\nwhen the sun warms them after a cold night.\n\nHe thanked Beatrice and Virgil,\njoined his will to Virgil's,\nand entered the deep savage path.",
    "notes": "<div class=\"note-block\"><strong>Three blessed ladies:</strong> Mary, Lucia, and Beatrice form a ladder of mercy. This is important background for the whole Comedy: salvation comes through grace before Dante even understands it.</div><div class=\"note-block\"><strong>The flower image:</strong> Dante's courage returns like flowers opening in sunlight. The image answers the cold darkness of fear with warmth, growth, and trust.</div><div class=\"note-block\"><strong>Leader, lord, master:</strong> Dante gives Virgil authority for the journey. The canto ends with Dante choosing to follow, not because fear is gone forever, but because trust has become stronger.</div>"
  },
  {
    "canto": 3,
    "title": "The Gate of Hell and Acheron",
    "lines": "Canto 3, scene 1",
    "classic": "“Through me the way is to the city dolent;\n    Through me the way is to eternal dole;\n    Through me the way among the people lost.\nJustice incited my sublime Creator;\n    Created me divine Omnipotence,\n    The highest Wisdom and the primal Love.\nBefore me there were no created things,\n    Only eterne, and I eternal last.\n    All hope abandon, ye who enter in!”\nThese words in sombre colour I beheld\n    Written upon the summit of a gate;\n    Whence I: “Their sense is, Master, hard to me!”\nAnd he to me, as one experienced:\n    “Here all suspicion needs must be abandoned,\n    All cowardice must needs be here extinct.\nWe to the place have come, where I have told thee\n    Thou shalt behold the people dolorous\n    Who have foregone the good of intellect.”\nAnd after he had laid his hand on mine\n    With joyful mien, whence I was comforted,\n    He led me in among the secret things.\nThere sighs, complaints, and ululations loud\n    Resounded through the air without a star,\n    Whence I, at the beginning, wept thereat.",
    "modern": "They reached the gate of Hell.\nThe words written above it said\nthat through this doorway\none enters grief, eternal pain,\nand the city of the lost.\n\nThe inscription says Hell was made\nby divine power, wisdom, justice, and love.\nThen comes the terrible final line:\nAbandon every hope,\nyou who enter here.",
    "notes": "<div class=\"note-block\"><strong>The gate of Hell:</strong> This is the first formal threshold. Dante is no longer near danger; he is entering the realm where sin's consequences are revealed.</div><div class=\"note-block\"><strong>Justice and love:</strong> The inscription says Hell comes from divine justice, power, wisdom, and even love. That is difficult for modern readers, but Dante's idea is that evil must be seen truthfully and judged rightly.</div><div class=\"note-block\"><strong>Abandon hope:</strong> Hell is defined by hopelessness. Purgatory will hurt too, but it has hope. Hell does not.</div>"
  },
  {
    "canto": 3,
    "title": "The Gate of Hell and Acheron",
    "lines": "Canto 3, scene 2",
    "classic": "Languages diverse, horrible dialects,\n    Accents of anger, words of agony,\n    And voices high and hoarse, with sound of hands,\nMade up a tumult that goes whirling on\n    For ever in that air for ever black,\n    Even as the sand doth, when the whirlwind breathes.\nAnd I, who had my head with horror bound,\n    Said: “Master, what is this which now I hear?\n    What folk is this, which seems by pain so vanquished?”\nAnd he to me: “This miserable mode\n    Maintain the melancholy souls of those\n    Who lived withouten infamy or praise.\nCommingled are they with that caitiff choir\n    Of Angels, who have not rebellious been,\n    Nor faithful were to God, but were for self.\nThe heavens expelled them, not to be less fair;\n    Nor them the nethermore abyss receives,\n    For glory none the damned would have from them.”\nAnd I: “O Master, what so grievous is\n    To these, that maketh them lament so sore?”\n    He answered: “I will tell thee very briefly.\nThese have no longer any hope of death;\n    And this blind life of theirs is so debased,\n    They envious are of every other fate.",
    "modern": "Dante heard a chaos of sighs,\ncries, rage, pain, strange languages,\nand hands beating in the dark air.\n\nHe asked Virgil who these people were.\nVirgil explained that these were the souls\nwho lived without real blame\nand without real praise.\n\nThey never chose good or evil.\nThey chose only themselves.",
    "notes": "<div class=\"note-block\"><strong>The neutral souls:</strong> These are people who refused moral commitment. They were not famous villains; they were spiritually empty because they never stood for anything.</div><div class=\"note-block\"><strong>The angels:</strong> Dante also includes angels who supposedly took neither God's side nor Lucifer's. They chose self-preservation over allegiance.</div><div class=\"note-block\"><strong>Why Dante despises them:</strong> For Dante, refusing to choose the good is itself a disastrous choice. Moral cowardice is not innocence.</div>"
  },
  {
    "canto": 3,
    "title": "The Gate of Hell and Acheron",
    "lines": "Canto 3, scene 3",
    "classic": "No fame of them the world permits to be;\n    Misericord and Justice both disdain them.\n    Let us not speak of them, but look, and pass.”\nAnd I, who looked again, beheld a banner,\n    Which, whirling round, ran on so rapidly,\n    That of all pause it seemed to me indignant;\nAnd after it there came so long a train\n    Of people, that I ne’er would have believed\n    That ever Death so many had undone.\nWhen some among them I had recognised,\n    I looked, and I beheld the shade of him\n    Who made through cowardice the great refusal.\nForthwith I comprehended, and was certain,\n    That this the sect was of the caitiff wretches\n    Hateful to God and to his enemies.\nThese miscreants, who never were alive,\n    Were naked, and were stung exceedingly\n    By gadflies and by hornets that were there.\nThese did their faces irrigate with blood,\n    Which, with their tears commingled, at their feet\n    By the disgusting worms was gathered up.\nAnd when to gazing farther I betook me.\n    People I saw on a great river’s bank;\n    Whence said I: “Master, now vouchsafe to me,",
    "modern": "These souls are rejected by Heaven\nand not fully accepted by Hell.\nThey have no fame,\nno hope of death,\nand they envy every other fate.\n\nThey chase a spinning banner forever,\njust as in life they chased whatever\nwas easiest, safest, or most convenient.\n\nThey are stung by insects,\nand worms gather their blood and tears.",
    "notes": "<div class=\"note-block\"><strong>The banner:</strong> In life they followed no stable principle, so in death they run forever after a meaningless moving sign.</div><div class=\"note-block\"><strong>No fame:</strong> Dante treats memory as morally important. These souls are so empty that the world is not allowed to remember them.</div><div class=\"note-block\"><strong>The insects and worms:</strong> Their punishment is ugly, restless, and humiliating. The blood and tears they never spent for a worthy cause become food for worms.</div>"
  },
  {
    "canto": 3,
    "title": "The Gate of Hell and Acheron",
    "lines": "Canto 3, scene 4",
    "classic": "That I may know who these are, and what law\n    Makes them appear so ready to pass over,\n    As I discern athwart the dusky light.”\nAnd he to me: “These things shall all be known\n    To thee, as soon as we our footsteps stay\n    Upon the dismal shore of Acheron.”\nThen with mine eyes ashamed and downward cast,\n    Fearing my words might irksome be to him,\n    From speech refrained I till we reached the river.\nAnd lo! towards us coming in a boat\n    An old man, hoary with the hair of eld,\n    Crying: “Woe unto you, ye souls depraved!\nHope nevermore to look upon the heavens;\n    I come to lead you to the other shore,\n    To the eternal shades in heat and frost.\nAnd thou, that yonder standest, living soul,\n    Withdraw thee from these people, who are dead!”\n    But when he saw that I did not withdraw,\nHe said: “By other ways, by other ports\n    Thou to the shore shalt come, not here, for passage;\n    A lighter vessel needs must carry thee.”\nAnd unto him the Guide: “Vex thee not, Charon;\n    It is so willed there where is power to do\n    That which is willed; and farther question not.”",
    "modern": "Dante then saw a crowd\nwaiting on the bank of a dark river.\nHe asked who they were\nand why they seemed so ready to cross.\n\nVirgil told him he would understand\nwhen they reached the shore of Acheron.\n\nThen Charon appeared,\nthe old ferryman of the dead,\nordering the damned souls into his boat.",
    "notes": "<div class=\"note-block\"><strong>Acheron:</strong> In classical mythology, Acheron is one of the rivers of the underworld. Dante blends classical underworld imagery with Christian theology.</div><div class=\"note-block\"><strong>Charon:</strong> Charon is the mythic ferryman who carries dead souls across the river. Dante turns him into a demonic servant of divine judgment.</div><div class=\"note-block\"><strong>Why they are eager:</strong> The souls fear punishment, but they are also driven toward it because their own guilt and divine justice compel them.</div>"
  },
  {
    "canto": 3,
    "title": "The Gate of Hell and Acheron",
    "lines": "Canto 3, scene 5",
    "classic": "Thereat were quieted the fleecy cheeks\n    Of him the ferryman of the livid fen,\n    Who round about his eyes had wheels of flame.\nBut all those souls who weary were and naked\n    Their colour changed and gnashed their teeth together,\n    As soon as they had heard those cruel words.\nGod they blasphemed and their progenitors,\n    The human race, the place, the time, the seed\n    Of their engendering and of their birth!\nThereafter all together they drew back,\n    Bitterly weeping, to the accursed shore,\n    Which waiteth every man who fears not God.\nCharon the demon, with the eyes of glede,\n    Beckoning to them, collects them all together,\n    Beats with his oar whoever lags behind.\nAs in the autumn-time the leaves fall off,\n    First one and then another, till the branch\n    Unto the earth surrenders all its spoils;\nIn similar wise the evil seed of Adam\n    Throw themselves from that margin one by one,\n    At signals, as a bird unto its lure.\nSo they depart across the dusky wave,\n    And ere upon the other side they land,\n    Again on this side a new troop assembles.",
    "modern": "Charon noticed Dante was alive\nand told him to leave the dead.\nVirgil silenced him with the same formula:\nthis journey is willed in Heaven,\nwhere will and power are one.\n\nThe damned souls cursed God,\ntheir parents,\nthe human race,\nand even the time and place of their birth.\n\nCharon gathered them\nand struck the slow ones with his oar.",
    "notes": "<div class=\"note-block\"><strong>Virgil's formula:</strong> \"It is so willed...\" means Dante's journey is authorized by Heaven. Even Hell's guardians cannot block what God permits.</div><div class=\"note-block\"><strong>Blasphemy:</strong> The damned curse everything except themselves. This shows their refusal to repent: they suffer, but they do not become humble.</div><div class=\"note-block\"><strong>Contrapasso preview:</strong> Dante's punishments often reveal the shape of the sin. Here, chaotic souls move in a chaotic crowd toward the judgment they resisted in life.</div>"
  },
  {
    "canto": 3,
    "title": "The Gate of Hell and Acheron",
    "lines": "Canto 3, scene 6",
    "classic": "“My son,” the courteous Master said to me,\n    “All those who perish in the wrath of God\n    Here meet together out of every land;\nAnd ready are they to pass o’er the river,\n    Because celestial Justice spurs them on,\n    So that their fear is turned into desire.\nThis way there never passes a good soul;\n    And hence if Charon doth complain of thee,\n    Well mayst thou know now what his speech imports.”\nThis being finished, all the dusk champaign\n    Trembled so violently, that of that terror\n    The recollection bathes me still with sweat.\nThe land of tears gave forth a blast of wind,\n    And fulminated a vermilion light,\n    Which overmastered in me every sense,\nAnd as a man whom sleep hath seized I fell.",
    "modern": "The souls fell toward the boat\nlike autumn leaves falling one by one.\nAs soon as one crowd crossed,\nanother gathered on the shore.\n\nVirgil explained that divine justice\npushes the damned toward judgment\nso that their fear becomes desire.\n\nThen the ground shook,\na red light flashed,\nand Dante fainted.",
    "notes": "<div class=\"note-block\"><strong>Autumn leaves:</strong> The image is beautiful and horrifying: countless souls fall naturally toward death, one after another.</div><div class=\"note-block\"><strong>Fear becomes desire:</strong> This is psychologically sharp. The damned do not want punishment as happiness; they are drawn toward the truth of what they have become.</div><div class=\"note-block\"><strong>Dante faints:</strong> Dante often collapses when emotion overwhelms him. His body cannot yet bear what his soul is being shown.</div>"
  },
  {
    "canto": 4,
    "title": "Limbo and the Noble Pagans",
    "lines": "Canto 4, scene 1",
    "classic": "Broke the deep lethargy within my head\n    A heavy thunder, so that I upstarted,\n    Like to a person who by force is wakened;\nAnd round about I moved my rested eyes,\n    Uprisen erect, and steadfastly I gazed,\n    To recognise the place wherein I was.\nTrue is it, that upon the verge I found me\n    Of the abysmal valley dolorous,\n    That gathers thunder of infinite ululations.\nObscure, profound it was, and nebulous,\n    So that by fixing on its depths my sight\n    Nothing whatever I discerned therein.\n“Let us descend now into the blind world,”\n    Began the Poet, pallid utterly;\n    “I will be first, and thou shalt second be.”\nAnd I, who of his colour was aware,\n    Said: “How shall I come, if thou art afraid,\n    Who’rt wont to be a comfort to my fears?”\nAnd he to me: “The anguish of the people\n    Who are below here in my face depicts\n    That pity which for terror thou hast taken.\nLet us go on, for the long way impels us.”\n    Thus he went in, and thus he made me enter\n    The foremost circle that surrounds the abyss.",
    "modern": "Dante woke from his faint\nbecause a great thunder shook him.\nHe found himself standing\non the edge of a deep valley\nfilled with endless sighing.\n\nVirgil was pale,\nand Dante thought he was afraid.\nBut Virgil explained\nthat his face showed pity,\nnot fear.",
    "notes": "<div class=\"note-block\"><strong>Where are they?</strong> Dante has crossed Acheron without describing the boat ride. He wakes on the edge of Hell proper.</div><div class=\"note-block\"><strong>Virgil's pallor:</strong> Dante thinks Virgil is afraid, but Virgil is grieving. This matters because Virgil belongs to the place they are about to enter.</div><div class=\"note-block\"><strong>Pity versus fear:</strong> The guide is not immune to sorrow. Reason can understand Hell, but it can still suffer from compassion.</div>"
  },
  {
    "canto": 4,
    "title": "Limbo and the Noble Pagans",
    "lines": "Canto 4, scene 2",
    "classic": "There, as it seemed to me from listening,\n    Were lamentations none, but only sighs,\n    That tremble made the everlasting air.\nAnd this arose from sorrow without torment,\n    Which the crowds had, that many were and great,\n    Of infants and of women and of men.\nTo me the Master good: “Thou dost not ask\n    What spirits these, which thou beholdest, are?\n    Now will I have thee know, ere thou go farther,\nThat they sinned not; and if they merit had,\n    ’Tis not enough, because they had not baptism\n    Which is the portal of the Faith thou holdest;\nAnd if they were before Christianity,\n    In the right manner they adored not God;\n    And among such as these am I myself.\nFor such defects, and not for other guilt,\n    Lost are we and are only so far punished,\n    That without hope we live on in desire.”\nGreat grief seized on my heart when this I heard,\n    Because some people of much worthiness\n    I knew, who in that Limbo were suspended.\n“Tell me, my Master, tell me, thou my Lord,”\n    Began I, with desire of being certain\n    Of that Faith which o’ercometh every error,",
    "modern": "They entered the first circle of Hell,\ncalled Limbo.\nThere were no screams there,\nonly sighs.\n\nThe souls suffered sorrow\nwithout physical torment.\nVirgil explained that they had not sinned,\nbut they lacked baptism\nand did not worship God\nin the Christian way.\n\nVirgil himself belongs there.",
    "notes": "<div class=\"note-block\"><strong>Limbo:</strong> Limbo is the first circle of Hell, but it is not fiery torment. Its pain is deprivation: noble souls desire God but cannot reach Him.</div><div class=\"note-block\"><strong>Baptism:</strong> In Catholic Christianity, baptism is the sacrament of entry into the Christian life. Dante's theology treats lack of baptism as a tragic barrier, even for virtuous people.</div><div class=\"note-block\"><strong>Hard idea:</strong> This canto can feel morally uncomfortable. Dante is honoring pagans and unbaptized infants while still placing them outside salvation. That tension is the point.</div>"
  },
  {
    "canto": 4,
    "title": "Limbo and the Noble Pagans",
    "lines": "Canto 4, scene 3",
    "classic": "“Came any one by his own merit hence,\n    Or by another’s, who was blessed thereafter?”\n    And he, who understood my covert speech,\nReplied: “I was a novice in this state,\n    When I saw hither come a Mighty One,\n    With sign of victory incoronate.\nHence he drew forth the shade of the First Parent,\n    And that of his son Abel, and of Noah,\n    Of Moses the lawgiver, and the obedient\nAbraham, patriarch, and David, king,\n    Israel with his father and his children,\n    And Rachel, for whose sake he did so much,\nAnd others many, and he made them blessed;\n    And thou must know, that earlier than these\n    Never were any human spirits saved.”\nWe ceased not to advance because he spake,\n    But still were passing onward through the forest,\n    The forest, say I, of thick-crowded ghosts.\nNot very far as yet our way had gone\n    This side the summit, when I saw a fire\n    That overcame a hemisphere of darkness.\nWe were a little distant from it still,\n    But not so far that I in part discerned not\n    That honourable people held that place.",
    "modern": "Dante asked whether anyone\never escaped Limbo.\nVirgil said yes:\na mighty victorious one came there\nand took Adam, Abel, Noah, Moses,\nAbraham, David, Israel, Rachel,\nand many others into blessedness.\n\nBefore that,\nno human soul had been saved.",
    "notes": "<div class=\"note-block\"><strong>The Mighty One:</strong> This refers to Christ. Dante is alluding to the Harrowing of Hell, the belief that Christ descended to the dead after the Crucifixion and freed righteous Hebrew patriarchs.</div><div class=\"note-block\"><strong>Names listed:</strong> Adam, Noah, Moses, Abraham, David, Israel, and Rachel are major Hebrew Bible figures. They belong to sacred history before Christianity.</div><div class=\"note-block\"><strong>Why they leave:</strong> They are saved not by classical virtue alone, but by Christ's victory. This reinforces Dante's distinction between noble human goodness and divine grace.</div>"
  },
  {
    "canto": 4,
    "title": "Limbo and the Noble Pagans",
    "lines": "Canto 4, scene 4",
    "classic": "“O thou who honourest every art and science,\n    Who may these be, which such great honour have,\n    That from the fashion of the rest it parts them?”\nAnd he to me: “The honourable name,\n    That sounds of them above there in thy life,\n    Wins grace in Heaven, that so advances them.”\nIn the mean time a voice was heard by me:\n    “All honour be to the pre-eminent Poet;\n    His shade returns again, that was departed.”\nAfter the voice had ceased and quiet was,\n    Four mighty shades I saw approaching us;\n    Semblance had they nor sorrowful nor glad.\nTo say to me began my gracious Master:\n    “Him with that falchion in his hand behold,\n    Who comes before the three, even as their lord.\nThat one is Homer, Poet sovereign;\n    He who comes next is Horace, the satirist;\n    The third is Ovid, and the last is Lucan.\nBecause to each of these with me applies\n    The name that solitary voice proclaimed,\n    They do me honour, and in that do well.”\nThus I beheld assemble the fair school\n    Of that lord of the song pre-eminent,\n    Who o’er the others like an eagle soars.",
    "modern": "As they walked through the crowded ghosts,\nDante saw a fire shining\ninside the darkness.\nThere were honored souls there.\n\nA voice welcomed Virgil back,\nand four great poets approached:\nHomer, Horace, Ovid, and Lucan.\n\nThey greeted Virgil,\nand then they welcomed Dante\nas a sixth among them.",
    "notes": "<div class=\"note-block\"><strong>The noble pagans:</strong> Dante creates a place of honor inside loss. These souls are not mocked; they are dignified, luminous, and culturally magnificent.</div><div class=\"note-block\"><strong>The poets:</strong> Homer, Horace, Ovid, Lucan, and Virgil form Dante's imagined poetic lineage. Being welcomed by them is an enormous literary self-claim.</div><div class=\"note-block\"><strong>Dante as sixth:</strong> Dante quietly places himself among the greatest poets of antiquity. It is humble in tone but wildly ambitious in implication.</div>"
  },
  {
    "canto": 4,
    "title": "Limbo and the Noble Pagans",
    "lines": "Canto 4, scene 5",
    "classic": "When they together had discoursed somewhat,\n    They turned to me with signs of salutation,\n    And on beholding this, my Master smiled;\nAnd more of honour still, much more, they did me,\n    In that they made me one of their own band;\n    So that the sixth was I, ’mid so much wit.\nThus we went on as far as to the light,\n    Things saying ’tis becoming to keep silent,\n    As was the saying of them where I was.\nWe came unto a noble castle’s foot,\n    Seven times encompassed with lofty walls,\n    Defended round by a fair rivulet;\nThis we passed over even as firm ground;\n    Through portals seven I entered with these Sages;\n    We came into a meadow of fresh verdure.\nPeople were there with solemn eyes and slow,\n    Of great authority in their countenance;\n    They spake but seldom, and with gentle voices.\nThus we withdrew ourselves upon one side\n    Into an opening luminous and lofty,\n    So that they all of them were visible.\nThere opposite, upon the green enamel,\n    Were pointed out to me the mighty spirits,\n    Whom to have seen I feel myself exalted.",
    "modern": "The poets led Dante\nto a noble castle\nwith seven walls and seven gates,\nsurrounded by a gentle stream.\n\nInside was a green meadow\nfilled with solemn, dignified figures.\nDante saw heroes, rulers,\nand great women and men\nfrom ancient history and legend.",
    "notes": "<div class=\"note-block\"><strong>The castle:</strong> The seven walls and seven gates are often read as symbols of human virtue, learning, or the liberal arts. The place is beautiful, but still enclosed.</div><div class=\"note-block\"><strong>Green meadow:</strong> This is the closest Limbo gets to peace. It resembles an earthly paradise of culture and reason, but not Heaven.</div><div class=\"note-block\"><strong>Saladin:</strong> Dante includes the Muslim ruler Saladin among the noble spirits. This shows his admiration can cross religious boundaries, even within his Christian framework.</div>"
  },
  {
    "canto": 4,
    "title": "Limbo and the Noble Pagans",
    "lines": "Canto 4, scene 6",
    "classic": "I saw Electra with companions many,\n    ’Mongst whom I knew both Hector and Aeneas,\n    Caesar in armour with gerfalcon eyes;\nI saw Camilla and Penthesilea\n    On the other side, and saw the King Latinus,\n    Who with Lavinia his daughter sat;\nI saw that Brutus who drove Tarquin forth,\n    Lucretia, Julia, Marcia, and Cornelia,\n    And saw alone, apart, the Saladin.\nWhen I had lifted up my brows a little,\n    The Master I beheld of those who know,\n    Sit with his philosophic family.\nAll gaze upon him, and all do him honour.\n    There I beheld both Socrates and Plato,\n    Who nearer him before the others stand;\nDemocritus, who puts the world on chance,\n    Diogenes, Anaxagoras, and Thales,\n    Zeno, Empedocles, and Heraclitus;\nOf qualities I saw the good collector,\n    Hight Dioscorides; and Orpheus saw I,\n    Tully and Livy, and moral Seneca,\nEuclid, geometrician, and Ptolemy,\n    Galen, Hippocrates, and Avicenna,\n    Averroes, who the great Comment made.",
    "modern": "Then Dante saw Aristotle,\nwhom he calls the master of those who know,\nwith philosophers and thinkers around him:\nSocrates, Plato, Democritus,\nDiogenes, Euclid, Ptolemy,\nHippocrates, Avicenna, Averroes,\nand many more.",
    "notes": "<div class=\"note-block\"><strong>Aristotle:</strong> Medieval Christian thinkers treated Aristotle as the great philosopher of reason. Dante calls him the master of those who know.</div><div class=\"note-block\"><strong>Avicenna and Averroes:</strong> These were major Muslim philosophers whose work helped transmit and interpret Aristotle. Dante's intellectual world is broader than only Latin Christianity.</div><div class=\"note-block\"><strong>Medicine, geometry, astronomy:</strong> Limbo preserves the achievements of human knowledge. The tragedy is that knowledge alone is not salvation.</div>"
  },
  {
    "canto": 4,
    "title": "Limbo and the Noble Pagans",
    "lines": "Canto 4, scene 7",
    "classic": "I cannot all of them pourtray in full,\n    Because so drives me onward the long theme,\n    That many times the word comes short of fact.\nThe sixfold company in two divides;\n    Another way my sapient Guide conducts me\n    Forth from the quiet to the air that trembles;\nAnd to a place I come where nothing shines.",
    "modern": "Dante cannot name everyone.\nThe subject is too large,\nand the journey must continue.\n\nThe group divides.\nVirgil leads Dante away\nfrom the calm, honored place\nand back toward trembling air,\nto a place where nothing shines.",
    "notes": "<div class=\"note-block\"><strong>The exit from Limbo:</strong> Dante leaves a quiet, noble place for darkness again. The journey cannot remain in admiration of human greatness.</div><div class=\"note-block\"><strong>Nothing shines:</strong> The next circle is more actively painful. The descent is moving from deprivation into punishment.</div><div class=\"note-block\"><strong>Reader's clue:</strong> Canto IV teaches Dante to admire human greatness while recognizing its limits. That balance matters for the whole poem.</div>"
  },
  {
    "canto": 5,
    "title": "The Lustful and Francesca",
    "lines": "Canto 5, scene 1",
    "classic": "Thus I descended out of the first circle\n    Down to the second, that less space begirds,\n    And so much greater dole, that goads to wailing.\nThere standeth Minos horribly, and snarls;\n    Examines the transgressions at the entrance;\n    Judges, and sends according as he girds him.\nI say, that when the spirit evil-born\n    Cometh before him, wholly it confesses;\n    And this discriminator of transgressions\nSeeth what place in Hell is meet for it;\n    Girds himself with his tail as many times\n    As grades he wishes it should be thrust down.\nAlways before him many of them stand;\n    They go by turns each one unto the judgment;\n    They speak, and hear, and then are downward hurled.\n“O thou, that to this dolorous hostelry\n    Comest,” said Minos to me, when he saw me,\n    Leaving the practice of so great an office,\n“Look how thou enterest, and in whom thou trustest;\n    Let not the portal’s amplitude deceive thee.”\n    And unto him my Guide: “Why criest thou too?\nDo not impede his journey fate-ordained;\n    It is so willed there where is power to do\n    That which is willed; and ask no further question.”",
    "modern": "Dante descends into the second circle,\nwhere the space is smaller\nbut the pain is greater.\n\nAt the entrance stands Minos,\na monstrous judge.\nEach soul confesses everything,\nand Minos wraps his tail\naround himself the number of times\nthat marks how far down\nthe soul must go.",
    "notes": "<div class=\"note-block\"><strong>Second circle:</strong> This is the first circle of active punishment after Limbo. The sin here is lust: desire that overrules reason and moral responsibility.</div><div class=\"note-block\"><strong>Minos:</strong> In classical mythology, Minos is a judge of the dead. Dante makes him a grotesque infernal judge whose tail assigns souls to their circle.</div><div class=\"note-block\"><strong>Confession:</strong> The souls reveal themselves. Hell's judgment is not based on hidden evidence; the soul's own truth becomes visible.</div>"
  },
  {
    "canto": 5,
    "title": "The Lustful and Francesca",
    "lines": "Canto 5, scene 2",
    "classic": "And now begin the dolesome notes to grow\n    Audible unto me; now am I come\n    There where much lamentation strikes upon me.\nI came into a place mute of all light,\n    Which bellows as the sea does in a tempest,\n    If by opposing winds ’t is combated.\nThe infernal hurricane that never rests\n    Hurtles the spirits onward in its rapine;\n    Whirling them round, and smiting, it molests them.\nWhen they arrive before the precipice,\n    There are the shrieks, the plaints, and the laments,\n    There they blaspheme the puissance divine.\nI understood that unto such a torment\n    The carnal malefactors were condemned,\n    Who reason subjugate to appetite.\nAnd as the wings of starlings bear them on\n    In the cold season in large band and full,\n    So doth that blast the spirits maledict;\nIt hither, thither, downward, upward, drives them;\n    No hope doth comfort them for evermore,\n    Not of repose, but even of lesser pain.\nAnd as the cranes go chanting forth their lays,\n    Making in air a long line of themselves,\n    So saw I coming, uttering lamentations,",
    "modern": "Minos warns Dante\nnot to trust the wide entrance\nor enter carelessly.\n\nVirgil silences him:\nDante's journey is willed in Heaven.\n\nThen Dante hears louder suffering\nand enters a place without light,\nroaring like a storm-torn sea.",
    "notes": "<div class=\"note-block\"><strong>The warning:</strong> Minos tries to frighten Dante away, as Charon did. Each guardian recognizes that Dante is alive and does not belong there normally.</div><div class=\"note-block\"><strong>The wide entrance:</strong> The gate is easy to enter. That fits Dante's moral imagination: the road downward can seem open and effortless.</div><div class=\"note-block\"><strong>Storm imagery:</strong> The place sounds like a violent sea because the souls are no longer self-directed. They are carried by forces they once allowed to rule them.</div>"
  },
  {
    "canto": 5,
    "title": "The Lustful and Francesca",
    "lines": "Canto 5, scene 3",
    "classic": "Shadows borne onward by the aforesaid stress.\n    Whereupon said I: “Master, who are those\n    People, whom the black air so castigates?”\n“The first of those, of whom intelligence\n    Thou fain wouldst have,” then said he unto me,\n    “The empress was of many languages.\nTo sensual vices she was so abandoned,\n    That lustful she made licit in her law,\n    To remove the blame to which she had been led.\nShe is Semiramis, of whom we read\n    That she succeeded Ninus, and was his spouse;\n    She held the land which now the Sultan rules.\nThe next is she who killed herself for love,\n    And broke faith with the ashes of Sichaeus;\n    Then Cleopatra the voluptuous.”\nHelen I saw, for whom so many ruthless\n    Seasons revolved; and saw the great Achilles,\n    Who at the last hour combated with Love.\nParis I saw, Tristan; and more than a thousand\n    Shades did he name and point out with his finger,\n    Whom Love had separated from our life.\nAfter that I had listened to my Teacher,\n    Naming the dames of eld and cavaliers,\n    Pity prevailed, and I was nigh bewildered.",
    "modern": "A hurricane drives the souls forever,\nthrowing them up, down,\nand side to side.\nThey have no hope of rest,\nnot even a little less pain.\n\nDante learns that these are the lustful:\npeople who let appetite\nrule over reason.",
    "notes": "<div class=\"note-block\"><strong>Contrapasso:</strong> The punishment matches the sin symbolically. In life these souls let passion sweep them away; in Hell they are literally swept forever by wind.</div><div class=\"note-block\"><strong>Reason and appetite:</strong> Dante is not saying love or desire is evil by itself. The problem is desire ruling reason, conscience, promise, and God.</div><div class=\"note-block\"><strong>No rest:</strong> The storm's endlessness shows the inner restlessness of uncontrolled appetite.</div>"
  },
  {
    "canto": 5,
    "title": "The Lustful and Francesca",
    "lines": "Canto 5, scene 4",
    "classic": "And I began: “O Poet, willingly\n    Speak would I to those two, who go together,\n    And seem upon the wind to be so light.”\nAnd, he to me: “Thou’lt mark, when they shall be\n    Nearer to us; and then do thou implore them\n    By love which leadeth them, and they will come.”\nSoon as the wind in our direction sways them,\n    My voice uplift I: “O ye weary souls!\n    Come speak to us, if no one interdicts it.”\nAs turtle-doves, called onward by desire,\n    With open and steady wings to the sweet nest\n    Fly through the air by their volition borne,\nSo came they from the band where Dido is,\n    Approaching us athwart the air malign,\n    So strong was the affectionate appeal.\n“O living creature gracious and benignant,\n    Who visiting goest through the purple air\n    Us, who have stained the world incarnadine,\nIf were the King of the Universe our friend,\n    We would pray unto him to give thee peace,\n    Since thou hast pity on our woe perverse.\nOf what it pleases thee to hear and speak,\n    That will we hear, and we will speak to you,\n    While silent is the wind, as it is now.",
    "modern": "Virgil points out famous lovers\nand figures of desire:\nSemiramis, Dido, Cleopatra,\nHelen, Achilles, Paris, Tristan,\nand many others.\n\nDante is overcome with pity.\nHe asks to speak to two souls\nwho move together lightly\non the wind.",
    "notes": "<div class=\"note-block\"><strong>The famous names:</strong> Dante lists legendary and historical figures associated with sexual passion, tragic romance, or destructive desire.</div><div class=\"note-block\"><strong>Dido:</strong> Dido is the queen of Carthage in the Aeneid. She kills herself after Aeneas leaves her, so her appearance connects this canto back to Virgil's poem.</div><div class=\"note-block\"><strong>Dante's danger:</strong> Dante feels pity, and pity is human. But the canto will test whether pity can become morally confused when a sinner tells a beautiful story.</div>"
  },
  {
    "canto": 5,
    "title": "The Lustful and Francesca",
    "lines": "Canto 5, scene 5",
    "classic": "Sitteth the city, wherein I was born,\n    Upon the sea-shore where the Po descends\n    To rest in peace with all his retinue.\nLove, that on gentle heart doth swiftly seize,\n    Seized this man for the person beautiful\n    That was ta’en from me, and still the mode offends me.\nLove, that exempts no one beloved from loving,\n    Seized me with pleasure of this man so strongly,\n    That, as thou seest, it doth not yet desert me;\nLove has conducted us unto one death;\n    Caina waiteth him who quenched our life!”\n    These words were borne along from them to us.\nAs soon as I had heard those souls tormented,\n    I bowed my face, and so long held it down\n    Until the Poet said to me: “What thinkest?”\nWhen I made answer, I began: “Alas!\n    How many pleasant thoughts, how much desire,\n    Conducted these unto the dolorous pass!”\nThen unto them I turned me, and I spake,\n    And I began: “Thine agonies, Francesca,\n    Sad and compassionate to weeping make me.\nBut tell me, at the time of those sweet sighs,\n    By what and in what manner Love conceded,\n    That you should know your dubious desires?”",
    "modern": "The two souls come when Dante calls them\nin the name of love.\n\nThe woman is Francesca.\nShe says love seized Paolo\nbecause of her beauty,\nthen seized her in return.\nLove led them both to one death.\n\nShe also says Caina waits\nfor the person who killed them.",
    "notes": "<div class=\"note-block\"><strong>Francesca and Paolo:</strong> Francesca da Rimini and Paolo Malatesta were real contemporaries of Dante, traditionally said to have been murdered by Francesca's husband, Gianciotto.</div><div class=\"note-block\"><strong>Caina:</strong> Caina is a region of the lowest Hell for traitors to family. Francesca says their killer belongs there, which shifts blame outward.</div><div class=\"note-block\"><strong>Her language:</strong> Francesca speaks beautifully and repeatedly says \"Love\" caused everything. Watch how her rhetoric makes sin sound passive, almost inevitable.</div>"
  },
  {
    "canto": 5,
    "title": "The Lustful and Francesca",
    "lines": "Canto 5, scene 6",
    "classic": "And she to me: “There is no greater sorrow\n    Than to be mindful of the happy time\n    In misery, and that thy Teacher knows.\nBut, if to recognise the earliest root\n    Of love in us thou hast so great desire,\n    I will do even as he who weeps and speaks.\nOne day we reading were for our delight\n    Of Launcelot, how Love did him enthral.\n    Alone we were and without any fear.\nFull many a time our eyes together drew\n    That reading, and drove the colour from our faces;\n    But one point only was it that o’ercame us.\nWhen as we read of the much-longed-for smile\n    Being by such a noble lover kissed,\n    This one, who ne’er from me shall be divided,\nKissed me upon the mouth all palpitating.\n    Galeotto was the book and he who wrote it.\n    That day no farther did we read therein.”\nAnd all the while one spirit uttered this,\n    The other one did weep so, that, for pity,\n    I swooned away as if I had been dying,\nAnd fell, even as a dead body falls.",
    "modern": "Dante asks how their love began.\nFrancesca says they were reading\nabout Lancelot and Guinevere.\nThey were alone and unsuspecting.\n\nWhen the story reached the kiss,\nPaolo kissed her.\nThe book became their go-between.\nThat day, she says,\nthey read no further.\n\nPaolo weeps while she speaks.\nDante is so overwhelmed with pity\nthat he faints like a dead body.",
    "notes": "<div class=\"note-block\"><strong>Lancelot:</strong> Lancelot and Guinevere are lovers from Arthurian romance. Their adulterous love story becomes the spark for Paolo and Francesca's own adultery.</div><div class=\"note-block\"><strong>Galeotto:</strong> Galehaut, or Galeotto, was the go-between who helped Lancelot and Guinevere. Francesca says the book and its author played that role for her and Paolo.</div><div class=\"note-block\"><strong>Why Dante faints:</strong> He is overwhelmed by beauty, pity, and horror. The reader is meant to feel the attraction of Francesca's story and also notice what she leaves out: repentance, responsibility, and God.</div>"
  }
];
